name: Rebuild Homeroom images

on:
  schedule:
    - cron: '0 1 * * *' # everyday at 1am
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build only
        run: hack/build.sh -l local
        if: github.ref != 'refs/heads/develop'

      - name: Build and push
        run: hack/build.sh -l quay
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/develop'
